model:
  model_type: "microsoft/Florence-2-large-ft"  # change if needed
  lora_config: "configs/lora_config.yaml"
  init_checkpoint: "checkpoints/mimic_model_init.pt"
  processor:
    image_size: 128
    crop_size: 128
  peft:
    use_peft: True
    lora_checkpoint: "False"
  finetune: true

trainer:
  checkpoint_dir: "../outputs"
  project_name: "Knowledge-AG"  # wandb project name
  entity_name: "compai"   # wandb entity name
  max_epochs: 50  # change please!
  train_batch_size: 10
  valid_batch_size: 10
  num_workers: 0  # number of subprocesses for data loading, can be higher if more system resources
  log_every_n_steps: 100
  gpu: 0
  ddp: false
  optimizer: "adamw"
  learning_rate: 3e-6   # this was 3e-6 before
  weight_decay: 0.01

dataset:
  # need to change these paths if source files are moved
  padchest:
    img_root: "../padchest_images/"
    annotation_csv: "../padchest_labels_truncated.csv"
    data_pct: 1.0

  vindr:
    img_root: "E:/vinbigdata_xrays/vinbigdata/train/png"  # only the training set is annotated
    dicom_root: "E:/vinbigdata_xrays/vinbigdata/train/dicom"  # file path for the original DICOM images
    annotation_csv: "E:/vinbigdata_xrays/vinbigdata/train.csv"
    data_pct: 1.0


