copd signs: "copd signs"
chilaiditi sign: "chilaiditi sign"
nsg tube: "nsg tube"
abnormal foreign body: "abnormal foreign body"
abscess: "abscess"
adenopathy: "adenopathy"
air bronchogram: "air bronchogram"
air fluid level: "air fluid level"
air trapping: "air trapping"
alveolar pattern: "alveolar pattern"
aortic aneurysm: "aortic aneurysm"
aortic atheromatosis: "aortic atheromatosis"
aortic button enlargement: "aortic button enlargement"
aortic elongation: "aortic elongation"
aortic endoprosthesis: "aortic endoprosthesis"
apical pleural thickening: "apical pleural thickening"
artificial aortic heart valve: "artificial aortic heart valve"
artificial heart valve: "artificial heart valve"
artificial mitral heart valve: "artificial mitral heart valve"
asbestosis signs: "asbestosis signs"
ascendent aortic elongation: "ascendent aortic elongation"
atelectasis: "atelectasis"
atelectasis basal: "atelectasis basal"
atypical pneumonia: "atypical pneumonia"
axial hyperostosis: "axial hyperostosis"
azygoesophageal recess shift: "azygoesophageal recess shift"
azygos lobe: "azygos lobe"
blastic bone lesion: "blastic bone lesion"
bone cement: "bone cement"
bone metastasis: "bone metastasis"
breast mass: "breast mass"
bronchiectasis: "bronchiectasis"
bronchovascular markings: "bronchovascular markings"
bullas: "bullas"
calcified adenopathy: "calcified adenopathy"
calcified densities: "calcified densities"
calcified fibroadenoma: "calcified fibroadenoma"
calcified granuloma: "calcified granuloma"
calcified mediastinal adenopathy: "calcified mediastinal adenopathy"
calcified pleural plaques: "calcified pleural plaques"
calcified pleural thickening: "calcified pleural thickening"
callus rib fracture: "callus rib fracture"
cardiomegaly: "cardiomegaly"
catheter: "catheter"
cavitation: "cavitation"
central vascular redistribution: "central vascular redistribution"
central venous catheter: "central venous catheter"
central venous catheter via jugular vein: "central venous catheter via jugular vein"
central venous catheter via subclavian vein: "central venous catheter via subclavian vein"
central venous catheter via umbilical vein: "central venous catheter via umbilical vein"
cervical rib: "cervical rib"
chest drain tube: "chest drain tube"
chronic changes: "chronic changes"
clavicle fracture: "clavicle fracture"
consolidation: "consolidation"
costochondral junction hypertrophy: "costochondral junction hypertrophy"
costophrenic angle blunting: "costophrenic angle blunting"
cyst: "cyst"
dai: "dai"
descendent aortic elongation: "descendent aortic elongation"
dextrocardia: "dextrocardia"
diaphragmatic eventration: "diaphragmatic eventration"
double j stent: "double j stent"
dual chamber device: "dual chamber device"
electrical device: "electrical device"
emphysema: "emphysema"
empyema: "empyema"
end on vessel: "end on vessel"
endoprosthesis: "endoprosthesis"
endotracheal tube: "endotracheal tube"
esophagic dilatation: "esophagic dilatation"
exclude: "exclude"
external foreign body: "external foreign body"
fibrotic band: "fibrotic band"
fissure thickening: "fissure thickening"
flattened diaphragm: "flattened diaphragm"
fracture: "fracture"
gastrostomy tube: "gastrostomy tube"
goiter: "goiter"
granuloma: "granuloma"
ground glass pattern: "ground glass pattern"
gynecomastia: "gynecomastia"
heart insufficiency: "heart insufficiency"
heart valve calcified: "heart valve calcified"
hemidiaphragm elevation: "hemidiaphragm elevation"
hiatal hernia: "hiatal hernia"
hilar congestion: "hilar congestion"
hilar enlargement: "hilar enlargement"
humeral fracture: "humeral fracture"
humeral prosthesis: "humeral prosthesis"
hydropneumothorax: "hydropneumothorax"
hyperinflated lung: "hyperinflated lung"
hypoexpansion: "hypoexpansion"
hypoexpansion basal: "hypoexpansion basal"
increased density: "increased density"
infiltrates: "infiltrates"
interstitial pattern: "interstitial pattern"
kerley lines: "kerley lines"
kyphosis: "kyphosis"
laminar atelectasis: "laminar atelectasis"
lepidic adenocarcinoma: "lepidic adenocarcinoma"
lipomatosis: "lipomatosis"
lobar atelectasis: "lobar atelectasis"
loculated fissural effusion: "loculated fissural effusion"
loculated pleural effusion: "loculated pleural effusion"
lung metastasis: "lung metastasis"
lung vascular paucity: "lung vascular paucity"
lymphangitis carcinomatosa: "lymphangitis carcinomatosa"
lytic bone lesion: "lytic bone lesion"
major fissure thickening: "major fissure thickening"
mammary prosthesis: "mammary prosthesis"
mass: "mass"
mastectomy: "mastectomy"
mediastinal enlargement: "mediastinal enlargement"
mediastinal mass: "mediastinal mass"
mediastinal shift: "mediastinal shift"
mediastinic lipomatosis: "mediastinic lipomatosis"
metal: "metal"
miliary opacities: "miliary opacities"
minor fissure thickening: "minor fissure thickening"
multiple nodules: "multiple nodules"
nephrostomy tube: "nephrostomy tube"
nipple shadow: "nipple shadow"
nodule: "nodule"
non axial articular degenerative changes: "non axial articular degenerative changes"
normal: "normal"
obesity: "obesity"
osteopenia: "osteopenia"
osteoporosis: "osteoporosis"
osteosynthesis material: "osteosynthesis material"
pacemaker: "pacemaker"
pectum carinatum: "pectum carinatum"
pectum excavatum: "pectum excavatum"
pericardial effusion: "pericardial effusion"
pleural effusion: "pleural effusion"
pleural mass: "pleural mass"
pleural plaques: "pleural plaques"
pleural thickening: "pleural thickening"
pneumomediastinum: "pneumomediastinum"
pneumonia: "pneumonia"
pneumoperitoneo: "pneumoperitoneo"
pneumothorax: "pneumothorax"
post radiotherapy changes: "post radiotherapy changes"
prosthesis: "prosthesis"
pseudonodule: "pseudonodule"
pulmonary artery enlargement: "pulmonary artery enlargement"
pulmonary artery hypertension: "pulmonary artery hypertension"
pulmonary edema: "pulmonary edema"
pulmonary fibrosis: "pulmonary fibrosis"
pulmonary hypertension: "pulmonary hypertension"
pulmonary mass: "pulmonary mass"
pulmonary venous hypertension: "pulmonary venous hypertension"
reservoir central venous catheter: "reservoir central venous catheter"
respiratory distress: "respiratory distress"
reticular interstitial pattern: "reticular interstitial pattern"
reticulonodular interstitial pattern: "reticulonodular interstitial pattern"
rib fracture: "rib fracture"
right sided aortic arch: "right sided aortic arch"
round atelectasis: "round atelectasis"
sclerotic bone lesion: "sclerotic bone lesion"
scoliosis: "scoliosis"
segmental atelectasis: "segmental atelectasis"
single chamber device: "single chamber device"
soft tissue mass: "soft tissue mass"
sternoclavicular junction hypertrophy: "sternoclavicular junction hypertrophy"
sternotomy: "sternotomy"
subacromial space narrowing: "subacromial space narrowing"
subcutaneous emphysema: "subcutaneous emphysema"
suboptimal study: "suboptimal study"
superior mediastinal enlargement: "superior mediastinal enlargement"
supra aortic elongation: "supra aortic elongation"
surgery: "surgery"
surgery breast: "surgery breast"
surgery heart: "surgery heart"
surgery humeral: "surgery humeral"
surgery lung: "surgery lung"
surgery neck: "surgery neck"
suture material: "suture material"
thoracic cage deformation: "thoracic cage deformation"
total atelectasis: "total atelectasis"
tracheal shift: "tracheal shift"
tracheostomy tube: "tracheostomy tube"
tuberculosis: "tuberculosis"
tuberculosis sequelae: "tuberculosis sequelae"
unchanged: "unchanged"
vascular hilar enlargement: "vascular hilar enlargement"
vascular redistribution: "vascular redistribution"
ventriculoperitoneal drain tube: "ventriculoperitoneal drain tube"
vertebral anterior compression: "vertebral anterior compression"
vertebral compression: "vertebral compression"
vertebral degenerative changes: "vertebral degenerative changes"
vertebral fracture: "vertebral fracture"
volume loss: "volume loss"